### ISSUE TITLE
NodeCameraView don't display

### ISSUE THREAD

**Issue by thinh185** [sieuhuflit/react-native-live-stream-rtmp-example#1]
Hey man, I forked project and run then bug appeear.
NodeCameraView dont display view of camera live stream
Please help me

**Comment by Nguyen-Thanh-Tung** [comment]
have you granted access to the application?

**Comment by sinparjp** [comment]
Hi ! i try to connect this app with azure rtmp live streaming, it this possible ?

**Comment by RupamShaw** [comment]
react-native run-ios for macOs High Sierra ver1013.6 gives error 
``` normal/x86_64/bignum-dtoa.o

error: Build input file cannot be found: '/srs/react-native-live-stream-rtmp-example/node_modules/react-native/third-party/double-conversion-1.1.5/src/bignum-dtoa.cc'
```

**Comment by aymather** [comment]
I'm also having this problem on my ios device. NodeCameraView is not showing my camera opening. I've tried doing this in a barebones app which I have a copy of in my github. Please let me know what I'm doing wrong :(

https://github.com/aymather/livestreamingTest

**Comment by sieuhuflit** [comment]
You guys using Android or iOS, if using Android need to enable **Camera** permission first then it'll show off. If using iOS I think you guy should try to set style width and height @thinh185 @aymather
