### ISSUE TITLE
Can't replay

### ISSUE THREAD

**Issue by LevanaS** [sieuhuflit/react-native-live-stream-rtmp-example#10]
Live function is work, when I end the live,  I click replay, server client error:
`2020-5-25 10:49:01 2200 [INFO] [rtmp connect] id=JBOUK85Z ip=::ffff:192.168.1.14 app=liveTest4 args={"app":"liveTest4","flashVer":"LNX 9,0,124,2","swfUrl":"","pageUrl":"","tcUrl":"rtmp://192.168.1.14:1935/live/Test4","fpad":false,"capabilities":15,"audioCodecs":4071,"videoCodecs":252,"videoFunction":1}
[NodeEvent on postConnect] id=JBOUK85Z args={"app":"liveTest4","flashVer":"LNX 9,0,124,2","swfUrl":"","pageUrl":"","tcUrl":"rtmp://192.168.1.14:1935/live/Test4","fpad":false,"capabilities":15,"audioCodecs":4071,"videoCodecs":252,"videoFunction":1}       
[NodeEvent on prePlay] id=JBOUK85Z StreamPath=/liveTest4/replayForTest2 args={}`

`2020-5-25 10:49:01 2200 [INFO] [rtmp play] Stream not found. id=JBOUK85Z streamPath=/liveTest4/replayForTest2  streamId=1      
stderr: ffmpeg version git-2020-05-19-74dfc88 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200513
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 46.100 / 56. 46.100
  libavcodec     58. 86.100 / 58. 86.100
  libavformat    58. 43.100 / 58. 43.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 82.100 /  7. 82.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
-c:v: Protocol not found
Did you mean file:-c:v?`
and the srceen is black,I don't know why. may I ask where the replayed video is stored,Your project is excellent! I would like to thank you for your answers!

**Comment by sieuhuflit** [comment]
Have you install `ffmpeg` on your machine yet ? 
Sometimes it delay a little bit => Because it need process save your video to your machine, so you can't play immediately.

``` 
1/ Can't replay video.
Make sure you are following live stream server step. Install ffmpeg and do extra step to Replay live stream video
```
