### ISSUE TITLE
only can live once 

### ISSUE THREAD

**Issue by LevanaS** [sieuhuflit/react-native-live-stream-rtmp-example#11]
Log in to an account and only live once. When I finish live once, click "Livestream Now" again. The page is on a blue background. It seems that my camera has not been called

**Comment by sieuhuflit** [comment]
Hmmm. ...  Because I'm migrate to v2 to make the login and account more clean. Just example to help you guy work with the concept of this RTMP server.
.... So it's may has some problem there
