### ISSUE TITLE
Product box In Demo V1

### ISSUE THREAD

**Issue by alfinurhakim** [sieuhuflit/react-native-live-stream-rtmp-example#13]
hello sir, I want to ask how to add a boxabove the chat product as demonstrated v1 ? 

like this : 
<img width="351" alt="Screen Shot 2020-07-07 at 14 53 11" src="https://user-images.githubusercontent.com/48195224/86741507-a1f88180-c061-11ea-9e77-c0b45fcb0260.png">

This mine : 
![WhatsApp Image 2020-07-07 at 14 50 15](https://user-images.githubusercontent.com/48195224/86741565-af157080-c061-11ea-8c95-e7f54d99135f.jpeg)

**Comment by sieuhuflit** [comment]
It's just a drag and drop animated. The horizontal one is flatlist and handle PanResponder for item.
But v1 is currently not maintained anymore, so I just remember like this

**Comment by blainerb4** [comment]
is it possible to get this product feature as a carousel on the livestream? @sieuhuflit

**Comment by sieuhuflit** [comment]
Of course, you can customize that , use PanResponder wrap outside of item in carousel @blainerb4
