### ISSUE TITLE
Làm thế nào để lấy SOCKET_IO_SERVER khi em muốn live stream bằng RTMP_SERVER của facebook?

### ISSUE THREAD

**Issue by nguyentuanit97** [sieuhuflit/react-native-live-stream-rtmp-example#15]
Em muốn live stream từ app của mình và share lên facebook. Em đã pull project của anh về chạy và chạy thành công cho đến khi bấm nút Start live video nhưng camera ko hiện lên? Có phải do 2 Server mặc định trong code ko còn support nữa mà phải tự thay bằng server thật của mình vào?

**Comment by sieuhuflit** [comment]
> Có phải do 2 Server mặc định trong code ko còn support nữa mà phải tự thay bằng server thật của mình vào?

Em phải chạy server thật của mình, em có thể check README để xem về repo server (https://github.com/sieuhuflit/live-tream-rtmp-server)

Ngoài ra camera không hiện lên còn có thể do quyền truy cập camera của thiết bị nữa. @tuannvitt
