### ISSUE TITLE
IOS camera is not Opened

### ISSUE THREAD

**Issue by Osamasomy** [sieuhuflit/react-native-live-stream-rtmp-example#18]
Hi, I just download your repo and its working absolute fine on android side but when on IOS camera is not open only blue screen is Appeared.

**Comment by sieuhuflit** [comment]
You can self check, sure sure, maybe layout problem because I check already has IOS permissions, so maybe layout problem @Osamasomy

**Comment by sultan-arshi** [comment]
did you solve it 
same this happened to me,
cam do not open, heart button is not working, messages not working
![IMG_271540BD1725-1](https://user-images.githubusercontent.com/18505536/172047584-d5adb41d-b060-4bfc-b58a-c7a8b916345f.jpeg)

**Comment by sieuhuflit** [comment]
This due to iOS simulator problem, it's will worked on real device
