### ISSUE TITLE
> Task :react-native-nodemediaclient:javaPreCompileDebug FAILED  

### ISSUE THREAD

**Issue by gouravroy09** [sieuhuflit/react-native-live-stream-rtmp-example#39]
![Screenshot 2022-10-04 215709](https://user-images.githubusercontent.com/6790486/193873977-2f6ad195-e008-4fa2-942e-caa2530458fa.png)

**Comment by sieuhuflit** [comment]
I'm just refactor whole of this, previous version pretty buggy
