### ISSUE TITLE
Cannot replay 

### ISSUE THREAD

**Issue by akokhlik** [sieuhuflit/react-native-live-stream-rtmp-example#4]
Hi,
I cannot replay stream in log print this.Can You help me ?

[NodeEvent on prePlay] id=W6HCBR4D StreamPath=/liveuser1/replayforuser1 args={}
10/12/2019 05:38:42 15455 [INFO] [rtmp play] Stream not found. id=W6HCBR4D streamPath=/liveuser1/replayforuser1  streamId=1
connection

**Comment by sieuhuflit** [comment]
This problem because you are missing ffmpeg on your machine. You can check extra step in https://github.com/sieuhuflit/live-tream-rtmp-server now. I'm just update it. @akokhlik
