### ISSUE TITLE
Do you know how can stream HD or FullHD?

### ISSUE THREAD

**Issue by cybercoder** [sieuhuflit/react-native-live-stream-rtmp-example#7]
When i set preset to 4, it just resize video not capture hd from camera! The server is great and tested and Android cam is tested using ```Larix Broadcaster``` too.

**Comment by sieuhuflit** [comment]
Nope. I didn't try yet. @cybercoder

**Comment by cybercoder** [comment]
> Hmmm. @cybercoder. I didn't try it, thanks for your note

I did use [node-media-server docker](https://www.npmjs.com/package/node-media-server) container as testing server.
It works using standard streaming protocols.

**Comment by sieuhuflit** [comment]
Cool. I'm already try using docker for rtmp server, but setup has some error and problem when install and setup ffmpeg for replay.
