### ISSUE TITLE
 you see the video if I close and re-broadcast

### ISSUE THREAD

**Issue by pulnec** [sieuhuflit/react-native-live-stream-rtmp-example#8]
Everything is working well, it is just happening to me that in order to see the video that is being transmitted the user who is in spectator mode has to enter the room, I finish my transmission at that moment and then I create it again, just at that moment the viewer begins to see what I transmit.
**I describe it in steps:**
1. User1 starts a live stream
2. User2 enters the room to see the transmission of User1 (At this point the video that is transmitted is not seen)
3. User1 closed my live stream and returned to the user list
4. User2 leaves an alert that tells me that the live stream is over, for the test do not close it, I stayed in the room and with the alert active.
5. User1 started the live stream again
6. User2 right at this moment that I am with the alert still active, apparently does as a replay and begins to see the transmission of User1

In general, I do not know why when you enter the room and the transmission is active, it is not seen, until the user who transmits closes it and recreates it without leaving the room.

I hope you can help me with this.

**Comment by deeprathod** [comment]
@pulnec  hi, i am trying to build the project from 2 days. I was able to run the project successfully and hosted the  server as well. However when i click on  **Begin Live** > Nothing happens. and when other user joins, it doesn't show anything. 

Can you help me with the same? Thanks

**Comment by pulnec** [comment]
@deeprathod , If everything is working for you, it may be that the same thing happens to me, try to start a live stream, then enter another room with the other user, close the live stream and recreate it, without the user leaving the room. See if the video is activated at that moment is that you can see me.

I'm still going to evaluate the code to see if I can solve this case.

**Comment by deeprathod** [comment]
Hi @pulnec  Thank you very much for your reply, thought i am sailing alone in this boat, with no hope. 

You mean distancing does any effect ?  I just tried it with distancing and using different internet service providers in my iOS & Android application, but sadly the same result. 

Below are the events i was able to get in iOS & Android both. 

`livestream[11799:6709944] [] nw_socket_handle_socket_event [C3.1:1] Socket SO_ERROR [61: Connection refused]
nw_connection_get_connected_socket on unconnected nw_connection
TCP Conn 0x281efe100 Failed : error 0:61
videoDevice lockForConfiguration returned error (null)
Unrecognized WebSocket connection option(s) `agent`, `perMessageDeflate`, `pfx`, `key`, `passphrase`, `cert`, `ca`, `ciphers`, `rejectUnauthorized`. Did you mean to put these under `headers`?`

**Comment by sieuhuflit** [comment]
Hi guys, I'm just update repo to version v2, refactor all code to make it more clean and less bug, hope this new version can help you guy @deeprathod @pulnec 

- The replay problem is because your local machine didn't install **ffmpeg (https://www.ffmpeg.org/download.html) yet.** 

- Because the replay action is using this command to re-cast

**Comment by pulnec** [comment]
Thank you very much for the support, for me this that you have programmed
is great, and later I would like to be able to help maintain it.

**Comment by sieuhuflit** [comment]
Thanks, hope this can help you @pulnec
